### ISSUE TITLE
Support for quiet global parameter

### ISSUE THREAD

**Issue by tzkmx** [trepmal/wp-revisions-cli#7]
I'm planning run this tool to give periodic maintenance to our databases, however its somewhat cumbersome running it in a cron script because the output of the progress bar. A check for the global `--quiet` parameter would be nice in order to not using it if the user has requested a silent run.

**Comment by trepmal** [comment]
`--quiet` by default doesn't suppress progress bars. For example, `wp post generate --count=1 --quiet` still outputs the bar.

You can always pipe to `/dev/null` to make sure nothing prints to stdout

```
wp revisions generate > /dev/null
```
